### ISSUE TITLE
Graphical artifacts running through ship sprites

### ISSUE THREAD

**Issue by alankistemaker** [a5c3nd3d/SWE20001-Battleships#15]
There are a number of graphical artifacts that cut through the ship sprites 
![image](https://cloud.githubusercontent.com/assets/20942757/18457889/ca831078-799f-11e6-9009-a2e9ca392bb7.png)

**Comment by a5c3nd3d** [comment]
Is this still an issue with the current iteration of the game?

**Comment by alankistemaker** [comment]
This is no longer and issue
